# renv activation script
# This file is auto-generated by renv; do not edit by hand.

local({

  # the requested version of renv
  version <- "1.0.7"
  attr(version, "sha") <- NULL

  # the project directory
  project <- getwd()

  # use start-up diagnostics if enabled
  diagnostics <- Sys.getenv("RENV_STARTUP_DIAGNOSTICS", unset = "FALSE")
  if (diagnostics) {
    start <- Sys.time()
    prefix <- "[renv startup diagnostics] "
    options(renv.startup.diagnostics = TRUE)
  }

  # figure out whether the autoloader is enabled
  enabled <- local({

    # first, check if the packrat autoloader is disabled
    disabled <- Sys.getenv("RENV_AUTOLOADER_ENABLED", unset = NA)
    if (!is.na(disabled)) {
      tolower(disabled) %in% c("true", "t", "1")
    }

    # next, check the option
    enabled <- getOption("renv.autoloader.enabled")
    if (!is.null(enabled)) {
      return(enabled)
    }

    # by default, use the autoloader
    TRUE

  })

  if (!enabled)
    return(FALSE)

  # avoid recursion
  if (identical(getOption("renv.autoloader.running"), TRUE)) {
    warning("ignoring recursive renv autoloader invocation")
    return(invisible(TRUE))
  }

  options(renv.autoloader.running = TRUE)
  on.exit(options(renv.autoloader.running = NULL), add = TRUE)

  # signal that we're loading renv during R startup
  Sys.setenv("RENV_R_INITIALIZING" = "true")
  on.exit(Sys.unsetenv("RENV_R_INITIALIZING"), add = TRUE)

  # load the 'utils' package eagerly -- this ensures that renv shims, which
  # mask 'utils' packages, parsing properly
  library(utils, lib.loc = .Library)

  # unload renv if it's already been loaded
  if ("renv" %in% loadedNamespaces())
    unloadNamespace("renv")

  # load bootstrap tools
  bootstrap <- function(version, library) {

    # read repos (respecting override if set)
    repos <- Sys.getenv("RENV_CONFIG_REPOS_OVERRIDE", unset = NA)
    if (is.na(repos))
      repos <- getOption("repos")

    # fix up repos
    on.exit(options(repos = repos), add = TRUE)
    repos[repos == "@CRAN@"] <- "https://cloud.r-project.org"
    options(repos = repos)

    # attempt to download renv
    tarball <- tryCatch(renv_bootstrap_download(version), error = identity)
    if (inherits(tarball, "error"))
      stop("failed to download renv ", version)

    # now attempt to install
    status <- tryCatch(renv_bootstrap_install(tarball, library), error = identity)
    if (inherits(status, "error"))
      stop("failed to install renv ", version)

  }

  renv_bootstrap_download <- function(version) {

    methods <- list(
      renv_bootstrap_download_cran_latest,
      renv_bootstrap_download_cran_archive
    )

    for (method in methods) {
      path <- tryCatch(method(version), error = identity)
      if (is.character(path) && file.exists(path))
        return(path)
    }

    stop("failed to download renv ", version)

  }

  renv_bootstrap_download_cran_latest <- function(version) {

    spec <- renv_bootstrap_download_cran_spec(version)
    type <- spec$type
    name <- spec$name

    repos <- getOption("repos")
    urls <- file.path(repos, "src/contrib", name)

    destdir <- tempdir()
    for (url in urls) {

      destfile <- file.path(destdir, name)
      status <- tryCatch(
        download.file(url, destfile, mode = "wb", quiet = TRUE),
        condition = identity
      )

      if (!inherits(status, "condition") && file.exists(destfile))
        return(destfile)

    }

    stop("failed to download renv")

  }

  renv_bootstrap_download_cran_archive <- function(version) {

    name <- sprintf("renv_%s.tar.gz", version)
    repos <- getOption("repos")
    urls <- file.path(repos, "src/contrib/Archive/renv", name)

    destdir <- tempdir()
    for (url in urls) {

      destfile <- file.path(destdir, name)
      status <- tryCatch(
        download.file(url, destfile, mode = "wb", quiet = TRUE),
        condition = identity
      )

      if (!inherits(status, "condition") && file.exists(destfile))
        return(destfile)

    }

    stop("failed to download renv")

  }

  renv_bootstrap_download_cran_spec <- function(version) {
    list(
      type = "source",
      name = sprintf("renv_%s.tar.gz", version)
    )
  }

  renv_bootstrap_install <- function(tarball, library) {

    dir.create(library, showWarnings = FALSE, recursive = TRUE)

    # attempt to install
    library <- normalizePath(library, winslash = "/", mustWork = TRUE)
    args <- c(
      "--vanilla", "CMD", "INSTALL", "--no-multiarch",
      "-l", shQuote(library),
      shQuote(tarball)
    )

    bin <- R.home("bin")
    exe <- if (Sys.info()[["sysname"]] == "Windows") "R.exe" else "R"
    R <- file.path(bin, exe)

    system2(R, args, stdout = NULL, stderr = NULL)

  }

  renv_bootstrap_run <- function(version, library) {

    # try to load renv from the library
    if (requireNamespace("renv", lib.loc = library, quietly = TRUE)) {
      return(renv::load(project = project))
    }

    # failed to load; attempt to bootstrap
    bootstrap(version, library)

    # try again to load
    if (requireNamespace("renv", lib.loc = library, quietly = TRUE)) {
      return(renv::load(project = project))
    }

    # failed to load renv; warn the user
    warning("failed to load renv from project library")

  }

  # construct path to library root
  root <- Sys.getenv("RENV_PATHS_LIBRARY_ROOT", unset = NA)
  if (is.na(root)) {
    root <- Sys.getenv("RENV_PATHS_LIBRARY", unset = NA)
    if (is.na(root)) {
      root <- "renv/library"
    }
  }

  # construct library path for renv
  prefix <- paste(R.version$platform, R.version$major, sep = "-")
  library <- file.path(root, prefix)

  # try to load renv
  renv_bootstrap_run(version, library)

  # report diagnostics
  if (diagnostics) {
    elapsed <- difftime(Sys.time(), start, units = "auto")
    message(sprintf("%s%.2f %s elapsed", prefix, elapsed, attr(elapsed, "units")))
  }

  invisible()

})
